---
title: "Wrap up"
author: "Mengyu Zhang"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(kinfitr)
library(knitr)
library(cowplot)
library(mgcv)
library(ggforce)
library(gnm)
library(data.table)
source("rcode/kinfitr_gnm.R")
source("rcode/pred_aif.R")
source("rcode/readdata.R")
source("rcode/slice_curve.R")
source("rcode/rising_mod.R")
source("rcode/plotcode.R")
source("rcode/add_bpr.R")
```

# Prepare data

```{r}
# load data
data = readdata()
# find tmax and slice the curve
data = data %>% 
  group_by(patient) %>% 
  mutate(count = map(count,~findtmax(.x)),
         count_asc = map(count, ~slice_asc(.x)), # data before tmax
         count_dsc = map(count, ~slice_exp(.x))) # data after tmax
```

# Fit model

```{r}
data = data %>% 
  group_by(patient) %>% 
  mutate(asc_res = map(count_asc, ~acs_inter(.x)), # detect t0 and interpolate aif between t0 and tmax
         count_asc = map(asc_res, ~.x$data), # add t0 to the data
         asc_mod = map(asc_res, ~.x$segmod), # save model that detecting t0
         dsc_mod = map(count_dsc, # fit nonlinear poisson regression for descending part
                       ~kinfitr_gnm(t = .x$time, # time since tmax
                                    t_G = .x$t_G, # time point put in gamma count since injection time
                                    y.sum = .x$count, 
                                    delta = .x$delta, # time in the gamma counter
                                    vol = .x$vol,
                                    pf = .x$parentFraction,
                                    bpr = .x$bpr,
                                    disp = rep(1,nrow(.x))
                                    )
                       ),
         dsc_mod = map(dsc_mod, ~.x$result), # save model fit data after tmax
         asc_pred = map(asc_res, ~.x$pred), # get prediction before tmax
         # get prediction after tmax, contain interpolated aif
         dsc_pred = map2(dsc_mod,count_dsc,~pred_aif(.x,.y)), 
         pred = map2(asc_pred,dsc_pred,~rbind(.x,.y$rsd[-1,])), # combine predicted aif
         rsd = map2(count, pred, ~add_residual(.x,.y)) # calculate residuals
         ) %>% 
  select(-asc_res)

```

# plot 

```{r}
for (i in 1:nrow(data)){
  par(mfrow=c(1,1))
  # change range of time by using 2nd and 3rd arguments
  scope_whole(data[i,],10,90) # plot aif and predicted aif
  plot_rsd(data[i,],10,90) # plot residuals and boxplot with median
}

```



